### ISSUE TITLE
As a NOI community App user I want to use my Open Data Hub credentials to access the NOI Community App.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.noi.community#18]
In order to integrate Keycloak in the NOI Community App we need to:
- [x] Receive the information about the template;
- [x] Implement a new template for the webview to be integrated in the app (#19 );
- [x] Integrate the Authentication in the Android version (https://github.com/noi-techpark/it.bz.noi.community.android/issues/83);
- [x] Integrate the Authentication in the iOS version (https://github.com/noi-techpark/it.bz.noi.community.ios/issues/94);

**Comment by Piiit** [comment]
@macteo @matax87 @sseppi

Hi all,
I will start the discussion here to provide you all needed information about oauth to login.

Found this repository: https://github.com/thomasdarimont/android-openid-connect/tree/feature/keycloak-oidc-demo

Maybe this is the way to go? It seems that we could create a "NOI Account" inside the system's account manager and just provide that to the application later on. Would that work?

On the other hand, I could just create the normal authentication flow that would redirect to a specific URL you give me with a valid access token if logged in correctly. I do not have experience how that would work with native apps...

In the meantime I create a client on keycloak and send you everything via mail...

Cheers,
Peter

**Comment by Piiit** [comment]
@sseppi Should we tick "Implement a new template for the webview to be integrated in the app"? The main issue has been closed...

**Comment by matax87** [comment]
> @macteo @matax87 @sseppi
> 
> Hi all, I will start the discussion here to provide you all needed information about oauth to login.
> 
> Found this repository: https://github.com/thomasdarimont/android-openid-connect/tree/feature/keycloak-oidc-demo
> 
> Maybe this is the way to go? It seems that we could create a "NOI Account" inside the system's account manager and just provide that to the application later on. Would that work?
> 
> On the other hand, I could just create the normal authentication flow that would redirect to a specific URL you give me with a valid access token if logged in correctly. I do not have experience how that would work with native apps...
> 
> In the meantime I create a client on keycloak and send you everything via mail...
> 
> Cheers, Peter

@Piiit I can confirm that we are able to perform a OAuth authentication with the provided client configuration.

![image](https://user-images.githubusercontent.com/4108197/153238673-1fee7041-2cd1-4dfa-a1b6-b3a55f20f682.png)

Moreover we were able to call the userInfo using the obtained access token:

```json
{
	"sub": "2ea1c57c-276f-4331-8cf8-08676bfaa6e5",
	"email_verified": true,
	"name": "Authentication Example User",
	"preferred_username": "authtestuser1",
	"given_name": "Authentication Example User",
	"locale": "de",
	"family_name": "",
	"email": "no-reply@opendatahub.bz.it"
}
```

**Comment by Piiit** [comment]
@chiaraDimension Please try the following: 

https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/logout?redirect_uri=https://noi.bz.it

The redirect_uri should be url encoded though... this is just a test, but just tell me which uri would be best

**Comment by Piiit** [comment]
Could it be in a native app, that you have a redirect similar to `noi-community://oauth2redirect/login-callback`, that shows then the login form of the app?

**Comment by chiaraDimension** [comment]
@Piiit 
`end_session_endpoint = https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/logout` is ok, but we need another `end_session_redirect_uri`. The documentation says:

> end_session_redirect_uri (required): The redirect URI to use for receiving the end session response. This should be a custom scheme URI (com.example.app:/oauth2redirect/example-provider). Consult the documentation for your authorization server.
> The value specified here should match the value specified for appAuthRedirectScheme in the build.gradle (Module: app), so that the demo app can capture the response.
> NOTE: Scheme of the URI should be the same as redirect_uri but callback should be different.

Can you configure `end_session_redirect_uri = noi-community://oauth2redirect/end_session-callback` on keycloak?

Maybe it could be useful if you also attach some screenshots of your configuration page, is it possible?

**Comment by Piiit** [comment]
Hi @chiaraDimension 

> Can you configure end_session_redirect_uri = noi-community://oauth2redirect/end_session-callback on keycloak?

Done

> Maybe it could be useful if you also attach some screenshots of your configuration page, is it possible?

![image](https://user-images.githubusercontent.com/6096063/154024570-19db891b-8330-4ed5-a408-7321cacb8078.png)

Hope this helps!

**Comment by Piiit** [comment]
All other settings have been kept with default values

**Comment by chiaraDimension** [comment]
Hi @Piiit,
could you provide us this data?

1. configuration for the production environment
2. some users for the production environment

**Comment by Piiit** [comment]
@chiaraDimension I created the same configuration on our production keycloak now as it is on the testing environment, the base url is as follows: https://auth.opendatahub.bz.it... you can register your own users, as the registration form is open and can be used by everyone --> accounts.opendatahub.bz.it + sign in

However, I wonder why we are not testing with the test environment I provided to you?

**Comment by Piiit** [comment]
@chiaraDimension I also added a role with name `ACCESS_GRANTED` to the login, please check for that and allow only access if it is present... let me know if you need further information

**Comment by matax87** [comment]
> ACCESS_GRANTED

@Piiit what we are suppose to do with it? Do we need to configure the OAuth flow in a specific way in order to check it or what?

**Comment by Piiit** [comment]
When you login you get a token, and the payload of that token contains roles and scopes (and other things), you just check if the role ACCESS_GRANTED exists for the client it.bz.noi.community, that's all... Keycloak just gives you that token and checks if the login is correct, but the authorization must be done by your logic, because we allow everyone freely to register. So we cannot allow everyone to access the app.

**Comment by Piiit** [comment]
> @Piiit the sign in page is also available via a direct URL? Because the UI has both a login and signup button.

I will forward this request and come back to you when I have a solution

**Comment by Piiit** [comment]
@matax87 The two urls are as follows:

https://auth.opendatahub.bz.it/auth/realms/noi/protocol/openid-connect/auth?client_id=it.bz.noi.community&redirect_uri=https://noi.bz.it&response_type=code&scope=openid
https://auth.opendatahub.bz.it/auth/realms/noi/protocol/openid-connect/registrations?client_id=it.bz.noi.community&redirect_uri=https://noi.bz.it&response_type=code&scope=openid

Change the base to https://auth.opendatahub.testingmachine.eu if you need the test environment

**Comment by matax87** [comment]
> When you login you get a token, and the payload of that token contains roles and scopes (and other things), you just check if the role ACCESS_GRANTED exists for the client it.bz.noi.community, that's all... Keycloak just gives you that token and checks if the login is correct, but the authorization must be done by your logic, because we allow everyone freely to register. So we cannot allow everyone to access the app.

@Piiit the payload doesn't contain any role. Do you have a working example?

```json
{
	"access_token": "eyJhbGciOiJ.g21w0w",
	"expires_in": 300,
	"refresh_expires_in": 3600,
	"refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlN2U0ZWJkZC0wODRhLTQwYTYtOWJmMi01ZGE2ZDNhOWY1OGIifQ.eyJleHAiOjE2NTA2Mzc5MTMsImlhdCI6MTY1MDYzNDMxMywianRpIjoiNzk1YjdjNjUtNDIzZS00ZWY0LTg5MTUtNGRiMmM2NDllMDA1IiwiaXNzIjoiaHR0cHM6Ly9hdXRoLm9wZW5kYXRhaHViLnRlc3RpbmdtYWNoaW5lLmV1L2F1dGgvcmVhbG1zL25vaSIsImF1ZCI6Imh0dHBzOi8vYXV0aC5vcGVuZGF0YWh1Yi50ZXN0aW5nbWFjaGluZS5ldS9hdXRoL3JlYWxtcy9ub2kiLCJzdWIiOiI2MWUzMDk3Ni1iOThjLTQwNjktYTQzNi1hNjBiYzlkMTQ2Y2UiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiaXQuYnoubm9pLmNvbW11bml0eSIsIm5vbmNlIjoid0lDVDh1WGNOQ2psNngyRDlnRW5DemlBVW9KNDFhYnpaclpGWGZuNy10QSIsInNlc3Npb25fc3RhdGUiOiJiNzE5MThlYy00ZmUxLTRhYjctYWIyOC1lYzgzYWEzZTg3OGQiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiYjcxOTE4ZWMtNGZlMS00YWI3LWFiMjgtZWM4M2FhM2U4NzhkIn0.aTs_imSysde-RtZELGsXyNiJ-spEvYposusgxkIBx44",
	"token_type": "Bearer",
	"id_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJVOXFqZ0dCb0tGclljTm5qdUMxZWVuRlpZb2pqQ1NYc3FVRWhlaE1HdjgwIn0.eyJleHAiOjE2NTA2MzQ2MTMsImlhdCI6MTY1MDYzNDMxMywiYXV0aF90aW1lIjoxNjUwNjM0MTI3LCJqdGkiOiI1NzJkYTE4OC05M2RiLTQwN2EtODllNi04OGU0ZGMxZTRlMmIiLCJpc3MiOiJodHRwczovL2F1dGgub3BlbmRhdGFodWIudGVzdGluZ21hY2hpbmUuZXUvYXV0aC9yZWFsbXMvbm9pIiwiYXVkIjoiaXQuYnoubm9pLmNvbW11bml0eSIsInN1YiI6IjYxZTMwOTc2LWI5OGMtNDA2OS1hNDM2LWE2MGJjOWQxNDZjZSIsInR5cCI6IklEIiwiYXpwIjoiaXQuYnoubm9pLmNvbW11bml0eSIsIm5vbmNlIjoid0lDVDh1WGNOQ2psNngyRDlnRW5DemlBVW9KNDFhYnpaclpGWGZuNy10QSIsInNlc3Npb25fc3RhdGUiOiJiNzE5MThlYy00ZmUxLTRhYjctYWIyOC1lYzgzYWEzZTg3OGQiLCJhdF9oYXNoIjoiRlljaTBveHJFdnVWR3E1UGJoTDNnZyIsImFjciI6IjAiLCJzaWQiOiJiNzE5MThlYy00ZmUxLTRhYjctYWIyOC1lYzgzYWEzZTg3OGQiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkF1dGhlbnRpY2F0aW9uIEV4YW1wbGUgVXNlciIsInByZWZlcnJlZF91c2VybmFtZSI6ImF1dGh0ZXN0dXNlcjIiLCJnaXZlbl9uYW1lIjoiQXV0aGVudGljYXRpb24gRXhhbXBsZSBVc2VyIiwibG9jYWxlIjoiZW4iLCJlbWFpbCI6Im5vLXJlcGx5MkBvcGVuZGF0YWh1Yi5iei5pdCJ9.A9PFp7GYuOj_Zs-f73s5W-Aa1ST68GcbSqd-cwGR5qH78zNfgX4CWX4bvJV3EDRQdaYoT_NiNdCIWFimCn-WkCeE94hj-MK5NiP6I1DORdwxc_oEbPABEiGbt4kFNVFB38yY0mB3zTIVP-IhWe9RdoGPhAqUG6CybxptGujAVGD1XiVNhuKWq8w_epdaCD4HTJ_JM28GA5CMX0qNdE08Z5RfcX_vc2-1jez5r-hM54vhO-ud4t1M-eqjCmXn1Id_X54apbZ9aCFCKhKadx-EFjfgqbqWUaB-z06ZPKC2cnBuDL6XYjDyJRqKbvAly31kT72DvpDigBgnMpBxX5FcNw",
	"not-before-policy": 1606215656,
	"session_state": "b71918ec-4fe1-4ab7-ab28-ec83aa3e878d",
	"scope": "openid email profile"
}
```

**Comment by macteo** [comment]
> but the authorization must be done by your logic

@Piiit this is pretty uncommon and a security risk as the client cannot be trusted. We can proceed anyway, but it must be acknowledged by NOI.

Also if you can help @matax87 solve the issue above as we are not able to see any role expressed in the payload.
Thanks

**Comment by Piiit** [comment]
> > When you login you get a token, and the payload of that token contains roles and scopes (and other things), you just check if the role ACCESS_GRANTED exists for the client it.bz.noi.community, that's all... Keycloak just gives you that token and checks if the login is correct, but the authorization must be done by your logic, because we allow everyone freely to register. So we cannot allow everyone to access the app.
> 
> @Piiit the payload doesn't contain any role. Do you have a working example?
> 
> ```json
> {
> 	"access_token": "eyJhbGciOiJ.g21w0w",
> 	"expires_in": 300,
> 	"refresh_expires_in": 3600,
> 	"refresh_token": "eyJhbGci...xkIBx44",
> 	"token_type": "Bearer",
> 	"id_token": "eyJhbGciOiJSUzI1NiIsInR5cCIg...BxX5FcNw",
> 	"not-before-policy": 1606215656,
> 	"session_state": "b71918ec-4fe1-4ab7-ab28-ec83aa3e878d",
> 	"scope": "openid email profile"
> }
> ```

Hi, I will give the two dimension users that privilege now

**Comment by Piiit** [comment]
> > but the authorization must be done by your logic
> 
> @Piiit this is pretty uncommon and a security risk as the client cannot be trusted. We can proceed anyway, but it must be acknowledged by NOI.
> 
> Also if you can help @matax87 solve the issue above as we are not able to see any role expressed in the payload. Thanks

You get a token that you can afterwards use for API calls, that token has been verified by Keycloak and is therefore authenticated. The login is general, where a logged user has different privileges. This is called role-based security on Keycloak, but if you forward then to the inner parts of the app is app specific and must be checked on app side. This is a normal workflow for this. It is not that we just check a flag, but a validated token.

**Comment by matax87** [comment]
> > > When you login you get a token, and the payload of that token contains roles and scopes (and other things), you just check if the role ACCESS_GRANTED exists for the client it.bz.noi.community, that's all... Keycloak just gives you that token and checks if the login is correct, but the authorization must be done by your logic, because we allow everyone freely to register. So we cannot allow everyone to access the app.
> > 
> > 
> > @Piiit the payload doesn't contain any role. Do you have a working example?
> > ```json
> > {
> > 	"access_token": "eyJhbGciOiJ.g21w0w",
> > 	"expires_in": 300,
> > 	"refresh_expires_in": 3600,
> > 	"refresh_token": "eyJhbGci...xkIBx44",
> > 	"token_type": "Bearer",
> > 	"id_token": "eyJhbGciOiJSUzI1NiIsInR5cCIg...BxX5FcNw",
> > 	"not-before-policy": 1606215656,
> > 	"session_state": "b71918ec-4fe1-4ab7-ab28-ec83aa3e878d",
> > 	"scope": "openid email profile"
> > }
> > ```
> 
> Hi, I will give the two dimension users that privilege now

@Piiit which users? We don't know their used id and password. Can you provide us this information via email? 

Thank you

**Comment by Piiit** [comment]
@matax87 You made them, the usernames are your emails... I had two users with `@dimension.it` emails

**Comment by Piiit** [comment]
@matax87 I understand, so please create accounts on the testing auth server and ping me afterwards, so I can give you the privileges to access the community app... see the comment above for the URL to do so. Let me know if you need any other information.

**Comment by matax87** [comment]
> @matax87 I understand, so please create accounts on the testing auth server and ping me afterwards, so I can give you the privileges to access the community app... see the comment above for the URL to do so. Let me know if you need any other information.

I've just created a generic one on DEV at DIMENSION dot IT

**Comment by Piiit** [comment]
Done, please test

**Comment by matax87** [comment]
> Done, please test

the payload still doesn't contain any role.

{
	"access_token": "eyJhbGciO...mysXgoXsuXpb8WoA",
	"expires_in": 300,
	"refresh_expires_in": 3600,
	"refresh_token": "eyJhbGciOiJIUzI1...FT910",
	"token_type": "Bearer",
	"id_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOi...LUBme70Q-Cg",
	"not-before-policy": 1606215656,
	"session_state": "8482ee1c-7252-4cbb-994f-3a733f89a186",
	"scope": "openid email profile"
}

**Comment by Piiit** [comment]
@matax87 The role is not in the response JSON, but in the token itself which is a JWT...this might also explain your concern in other comments. To verify my thoughts, please copy/paste the "access_token" content to https://jwt.io and see if you have there everything you need as JWT payload. Your application needs to decode that JWT as well and get the role from there. That should be an out-of-the-box command if you have a Keycloak or OAuth2 lib...

**Comment by matax87** [comment]
> @matax87 The role is not in the response JSON, but in the token itself which is a JWT...this might also explain your concern in other comments. To verify my thoughts, please copy/paste the "access_token" content to https://jwt.io and see if you have there everything you need as JWT payload. Your application needs to decode that JWT as well and get the role from there. That should be an out-of-the-box command if you have a Keycloak or OAuth2 lib...

Ok done. It was not clear that we had a jwt token from the oauth 2 flow.

Thank you!

**Comment by matax87** [comment]
@Piiit the auth flow is almost finished, but we have some doubts:

1. regarding the JWT token we also need to verify its signature or just the roles for our client id? 
2. the access token duration is 5 minutes and the refresh token duration is 60 minutes on the testing machine and 120 in the production one. For the testing machine these kind of durations are fine; but we think that on production they must be incremented/refresh token that never expires; otherwise, logged user will be automatically logged out.
